# prom_configurations/prometheus.yml

global:
  scrape_interval:     15s     # How often Prometheus will scrape targets

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['localhost:9100']